language: node_js
node_js:
- "0.10"
- "0.12"
env:
  global:
  - secure: t4ZqyR1nRG1LwzEpN6Pyv1l3jaC4CKuGiGjHNAjaIFYso/JDKp77veCx4pTIQWa4hVD0Vno25+FMUFAZTiWbs5q+K4gjBVG+H+WGX5z4Y9ClID7wsP7mYUkU3MqAdHTMK0/qq1EpBzTfXIloZntHkFTvVXlWu9YOlOigPqmk0pv5zI9jcpSsiW9H7XUymsnIyIobQicMFADOAvvPDCNnIVXvTojDgG19ohv7r1d4Q5fqmD4Cic7IlaAz78ZZ3EjTVmVxo8us7JawXwiV9z1LxIbdte+mcL6OGYFt8gSUXF5kPEs32UmyqJHNLiW1CxskEO7rmIONjjRgZWmhN8CpCSn91BDChK5dVUBXQGwK+ZjiVlK9lARdvFssZ1t5/2zR1c770VJ4R3J2lr0e7NsIeSubsO0OIEtvm4Su70fI+9mQrAjvt8rJusZv5G+qatJ+ir1Qby6+TcfNkqxkKGVE94z84BUSsSr2i46A3iVOGVBetHQzfnrgJMZh4JWL+gsmxMxWtKZbzbEj/QeuZPgHtUXd63lNOv2R46Jl61wp0vwShATDmgFKn2yYhZvqBj+PVVOYqqTigzA5CbqzgS3S/xa4bMgZglrtHLEZWKR8EpfpkVIhlIp6E2kP31zCLifbFSYQI1zsaf3olNRO/r7OrxRJyl/mX0n0SnytJ7x7g/A=
  - secure: bIPimJSkFnVvEL33GYlpsVS5Lo0CFx0saGT7hopyRvwM0sjlcjNmYHFzEbVOScA1/R7CpiiMTKRpB9Y9qtE6LjGU/Xqr/F+4jz3DiabMxzo5lRwvrVuVWWPSbubYLCujDUxIlntIINrHXqz063L82JKZlQ0K6KUtEwkajtOqDodg2r+f9znWSmaYknRA8yeU4BzbMJjR8Ay35KLlAriYbh0AKCUAxo9mvFEbg8GVK9olsMxhYZyORxLKCEau/GG0bu4d6yyjqkqTYKSXOghfgy+l7H61uC6x9kPHP2RCHowpdjHpBYtze+m+A3XJFOtngpMIpJHJ2z80HzqinHdrlMGYh4Hbe1yE2h4wzxvimWI2CW/GzkNnDj/VLpsxWkeok5nz6tYRyYFYaXInHZhBNcSCOvaRVo47tuWwMw+Vac4Wm0B9px9iDvZE51fVmZ47KBNao+kG0YmDkNMLbBK8Q7HIsRu3TWBUdXr7NkeOeLNDIR2nfQGtQhO8/j07S3+C+az/olsgmOBRVDRmhac3bVGD3ARpGWjnUV/owQuuhYTAxzAdSecR/+LL0zGhEdxhE/5IDfutIrtSggJgef1WqMA3XZGrwW9zvu9qhp1Bu6d4Lp/4QrPNkIbI0tukY+RIUGdUq+NZYgQFDa5k26gw+M4NHWPczO2P+8ePZLnu0Kw=
addons:
  code_climate:
    repo_token: 483a915e95c7f40a15b20f7df3ffe95e13e7f675c0aa7bf37412fc2183f15117
after_script:
  - codeclimate < lcov.info
